graph TD
    N0[codes.ts]
    N1[login.post.ts]
    N2[logout.post.ts]
    N3[refresh.post.ts]
    N4[bigint.ts]
    N5[all.ts]
    N6[status.ts]
    N7[.post.ts]
    N8[[id].delete.ts]
    N9[[id].put.ts]
    N10[list.ts]
    N11[list.ts]
    N12[name-exists.ts]
    N13[path-exists.ts]
    N14[list.ts]
    N15[list.ts]
    N16[test.get.ts]
    N17[test.post.ts]
    N18[getTimezone.ts]
    N19[getTimezoneOptions.ts]
    N20[setTimezone.ts]
    N21[upload.ts]
    N22[info.ts]
    N23[error.ts]
    N24[1.api.ts]
    N25[nitro.config.ts]
    N26[[...].ts]
    N27[cookie-utils.ts]
    N28[jwt-utils.ts]
    N29[mock-data.ts]
    N30[response.ts]
    N31[timezone-utils.ts]
    N32[index.ts]
    N33[form.ts]
    N34[vxe-table.ts]
    N35[auth.ts]
    N36[index.ts]
    N37[menu.ts]
    N38[user.ts]
    N39[index.ts]
    N40[request.ts]
    N41[bootstrap.ts]
    N42[index.ts]
    N43[index.ts]
    N44[main.ts]
    N45[preferences.ts]
    N46[access.ts]
    N47[guard.ts]
    N48[index.ts]
    N49[core.ts]
    N50[index.ts]
    N51[dashboard.ts]
    N52[demos.ts]
    N53[vben.ts]
    N54[auth.ts]
    N55[index.ts]
    N56[index.ts]
    N57[form.ts]
    N58[vxe-table.ts]
    N59[auth.ts]
    N60[index.ts]
    N61[menu.ts]
    N62[user.ts]
    N63[index.ts]
    N64[request.ts]
    N65[bootstrap.ts]
    N66[index.ts]
    N67[index.ts]
    N68[main.ts]
    N69[preferences.ts]
    N70[access.ts]
    N71[guard.ts]
    N72[index.ts]
    N73[core.ts]
    N74[index.ts]
    N75[dashboard.ts]
    N76[demos.ts]
    N77[vben.ts]
    N78[auth.ts]
    N79[index.ts]
    N80[index.ts]
    N81[form.ts]
    N82[vxe-table.ts]
    N83[auth.ts]
    N84[index.ts]
    N85[menu.ts]
    N86[user.ts]
    N87[index.ts]
    N88[request.ts]
    N89[bootstrap.ts]
    N90[index.ts]
    N91[index.ts]
    N92[main.ts]
    N93[preferences.ts]
    N94[access.ts]
    N95[guard.ts]
    N96[index.ts]
    N97[core.ts]
    N98[index.ts]
    N99[dashboard.ts]
    N100[demos.ts]
    N101[vben.ts]
    N102[auth.ts]
    N103[index.ts]
    N104[index.ts]
    N105[form.ts]
    N106[naive.ts]
    N107[vxe-table.ts]
    N108[auth.ts]
    N109[index.ts]
    N110[menu.ts]
    N111[user.ts]
    N112[index.ts]
    N113[request.ts]
    N114[bootstrap.ts]
    N115[index.ts]
    N116[index.ts]
    N117[main.ts]
    N118[preferences.ts]
    N119[access.ts]
    N120[guard.ts]
    N121[index.ts]
    N122[core.ts]
    N123[index.ts]
    N124[dashboard.ts]
    N125[demos.ts]
    N126[vben.ts]
    N127[auth.ts]
    N128[index.ts]
    N129[index.ts]
    N130[form.ts]
    N131[tdesign.ts]
    N132[vxe-table.ts]
    N133[auth.ts]
    N134[index.ts]
    N135[menu.ts]
    N136[user.ts]
    N137[index.ts]
    N138[request.ts]
    N139[bootstrap.ts]
    N140[index.ts]
    N141[index.ts]
    N142[main.ts]
    N143[preferences.ts]
    N144[access.ts]
    N145[guard.ts]
    N146[index.ts]
    N147[core.ts]
    N148[index.ts]
    N149[dashboard.ts]
    N150[demos.ts]
    N151[vben.ts]
    N152[auth.ts]
    N153[index.ts]
    N154[index.ts]
    N155[demo-preview.ts]
    N156[index.ts]
    N157[hm.ts]
    N158[index.ts]
    N159[component.ts]
    N160[form.ts]
    N161[vxe-table.ts]
    N162[form.ts]
    N163[vxe-table.ts]
    N164[mock-api.ts]
    N165[table-data.ts]
    N166[build.config.ts]
    N167[command.ts]
    N168[comments.ts]
    N169[disableds.ts]
    N170[ignores.ts]
    N171[import.ts]
    N172[index.ts]
    N173[javascript.ts]
    N174[jsdoc.ts]
    N175[jsonc.ts]
    N176[node.ts]
    N177[perfectionist.ts]
    N178[pnpm.ts]
    N179[prettier.ts]
    N180[regexp.ts]
    N181[tailwindcss.ts]
    N182[test.ts]
    N183[turbo.ts]
    N184[typescript.ts]
    N185[unicorn.ts]
    N186[vue.ts]
    N187[yaml.ts]
    N188[custom-config.ts]
    N189[index.ts]
    N190[util.ts]
    N191[build.config.ts]
    N192[hash.test.ts]
    N193[path.test.ts]
    N194[constants.ts]
    N195[date.ts]
    N196[fs.ts]
    N197[git.ts]
    N198[hash.ts]
    N199[index.ts]
    N200[monorepo.ts]
    N201[path.ts]
    N202[prettier.ts]
    N203[spinner.ts]
    N204[build.config.ts]
    N205[application.ts]
    N206[common.ts]
    N207[index.ts]
    N208[library.ts]
    N209[index.ts]
    N210[options.ts]
    N211[archiver.ts]
    N212[extra-app-config.ts]
    N213[importmap.ts]
    N214[index.ts]
    N215[index.ts]
    N216[inject-metadata.ts]
    N217[license.ts]
    N218[nitro-mock.ts]
    N219[print.ts]
    N220[tailwind-reference.ts]
    N221[vxe-table.ts]
    N222[typing.ts]
    N223[env.ts]
    N224[index.ts]
    N225[index.ts]
    N226[build.config.ts]
    N227[create-icon.ts]
    N228[index.ts]
    N229[lucide.ts]
    N230[build.config.ts]
    N231[storage-manager.test.ts]
    N232[index.ts]
    N233[storage-manager.ts]
    N234[types.ts]
    N235[convert.test.ts]
    N236[color.ts]
    N237[convert.ts]
    N238[generator.ts]
    N239[index.ts]
    N240[globals.ts]
    N241[index.ts]
    N242[vben.ts]
    N243[global-state.ts]
    N244[store.ts]
    N245[date.test.ts]
    N246[diff.test.ts]
    N247[dom.test.ts]
    N248[inference.test.ts]
    N249[letter.test.ts]
    N250[resources.test.ts]
    N251[stack.test.ts]
    N252[state-handler.test.ts]
    N253[tree.test.ts]
    N254[unique.test.ts]
    N255[update-css-variables.test.ts]
    N256[util.test.ts]
    N257[window.test.ts]
    N258[cn.ts]
    N259[date.ts]
    N260[diff.ts]
    N261[dom.ts]
    N262[download.ts]
    N263[index.ts]
    N264[inference.ts]
    N265[letter.ts]
    N266[merge.ts]
    N267[nprogress.ts]
    N268[resources.ts]
    N269[stack.ts]
    N270[state-handler.ts]
    N271[to.ts]
    N272[tree.ts]
    N273[unique.ts]
    N274[update-css-variables.ts]
    N275[util.ts]
    N276[window.ts]
    N277[build.config.ts]
    N278[app.d.ts]
    N279[basic.d.ts]
    N280[helper.d.ts]
    N281[index.ts]
    N282[menu-record.ts]
    N283[tabs.ts]
    N284[vue-router.d.ts]
    N285[vue-router.d.ts]
    N286[build.config.ts]
    N287[use-sortable.test.ts]
    N288[index.ts]
    N289[use-is-mobile.ts]
    N290[use-layout-style.ts]
    N291[use-namespace.ts]
    N292[use-priority-value.ts]
    N293[use-scroll-lock.ts]
    N294[index.ts]
    N295[messages.ts]
    N296[use-sortable.ts]
    N297[config.test.ts]
    N298[preferences.test.ts]
    N299[build.config.ts]
    N300[config.ts]
    N301[constants.ts]
    N302[index.ts]
    N303[preferences.ts]
    N304[types.ts]
    N305[update-css-variables.ts]
    N306[use-preferences.ts]
    N307[form-api.test.ts]
    N308[build.config.ts]
    N309[config.ts]
    N310[form-api.ts]
    N311[context.ts]
    N312[dependencies.ts]
    N313[expandable.ts]
    N314[helper.ts]
    N315[index.ts]
    N316[index.ts]
    N317[types.ts]
    N318[use-form-context.ts]
    N319[use-vben-form.ts]
    N320[build.config.ts]
    N321[index.ts]
    N322[index.ts]
    N323[use-layout.ts]
    N324[use-sidebar-drag.ts]
    N325[index.ts]
    N326[vben-layout.ts]
    N327[build.config.ts]
    N328[index.ts]
    N329[index.ts]
    N330[normal-menu.ts]
    N331[index.ts]
    N332[use-menu-context.ts]
    N333[use-menu-scroll.ts]
    N334[use-menu.ts]
    N335[index.ts]
    N336[types.ts]
    N337[index.ts]
    N338[build.config.ts]
    N339[AlertBuilder.ts]
    N340[alert.ts]
    N341[index.ts]
    N342[drawer-api.test.ts]
    N343[drawer-api.ts]
    N344[drawer.ts]
    N345[index.ts]
    N346[use-drawer.ts]
    N347[index.ts]
    N348[modal-api.test.ts]
    N349[index.ts]
    N350[modal-api.ts]
    N351[modal.ts]
    N352[use-modal-draggable.ts]
    N353[use-modal.ts]
    N354[build.config.ts]
    N355[index.ts]
    N356[backtop.ts]
    N357[index.ts]
    N358[use-backtop.ts]
    N359[index.ts]
    N360[types.ts]
    N361[button.ts]
    N362[index.ts]
    N363[index.ts]
    N364[index.ts]
    N365[interface.ts]
    N366[index.ts]
    N367[index.ts]
    N368[interface.ts]
    N369[index.ts]
    N370[index.ts]
    N371[index.ts]
    N372[index.ts]
    N373[index.ts]
    N374[index.ts]
    N375[index.ts]
    N376[index.ts]
    N377[types.ts]
    N378[index.ts]
    N379[index.ts]
    N380[index.ts]
    N381[index.ts]
    N382[types.ts]
    N383[index.ts]
    N384[index.ts]
    N385[index.ts]
    N386[index.ts]
    N387[index.ts]
    N388[index.ts]
    N389[index.ts]
    N390[avatar.ts]
    N391[index.ts]
    N392[badge.ts]
    N393[index.ts]
    N394[index.ts]
    N395[button.ts]
    N396[index.ts]
    N397[types.ts]
    N398[index.ts]
    N399[index.ts]
    N400[index.ts]
    N401[index.ts]
    N402[index.ts]
    N403[index.ts]
    N404[injectionKeys.ts]
    N405[useFormField.ts]
    N406[index.ts]
    N407[index.ts]
    N408[index.ts]
    N409[index.ts]
    N410[index.ts]
    N411[index.ts]
    N412[index.ts]
    N413[index.ts]
    N414[index.ts]
    N415[index.ts]
    N416[index.ts]
    N417[index.ts]
    N418[index.ts]
    N419[index.ts]
    N420[sheet.ts]
    N421[index.ts]
    N422[index.ts]
    N423[index.ts]
    N424[index.ts]
    N425[toggle.ts]
    N426[index.ts]
    N427[index.ts]
    N428[index.ts]
    N429[types.ts]
    N430[build.config.ts]
    N431[index.ts]
    N432[index.ts]
    N433[index.ts]
    N434[types.ts]
    N435[use-tabs-drag.ts]
    N436[use-tabs-view-scroll.ts]
    N437[core.ts]
    N438[index.ts]
    N439[accessible.ts]
    N440[directive.ts]
    N441[index.ts]
    N442[use-access.ts]
    N443[index.ts]
    N444[useCaptchaPoints.ts]
    N445[index.ts]
    N446[types.ts]
    N447[index.ts]
    N448[types.ts]
    N449[index.ts]
    N450[types.ts]
    N451[index.ts]
    N452[index.ts]
    N453[icons.ts]
    N454[index.ts]
    N455[index.ts]
    N456[index.ts]
    N457[types.ts]
    N458[directive.ts]
    N459[index.ts]
    N460[page.test.ts]
    N461[index.ts]
    N462[types.ts]
    N463[index.ts]
    N464[directive.ts]
    N465[index.ts]
    N466[index.ts]
    N467[index.ts]
    N468[about.ts]
    N469[index.ts]
    N470[index.ts]
    N471[types.ts]
    N472[index.ts]
    N473[index.ts]
    N474[typing.ts]
    N475[index.ts]
    N476[fallback.ts]
    N477[index.ts]
    N478[index.ts]
    N479[index.ts]
    N480[types.ts]
    N481[index.ts]
    N482[use-app-config.ts]
    N483[use-content-maximize.ts]
    N484[use-design-tokens.ts]
    N485[use-hover-toggle.ts]
    N486[use-pagination.ts]
    N487[use-refresh.ts]
    N488[use-tabs.ts]
    N489[use-watermark.ts]
    N490[index.ts]
    N491[types.ts]
    N492[index.ts]
    N493[use-content-spinner.ts]
    N494[index.ts]
    N495[index.ts]
    N496[index.ts]
    N497[index.ts]
    N498[index.ts]
    N499[use-extra-menu.ts]
    N500[use-mixed-menu.ts]
    N501[use-navigation.ts]
    N502[index.ts]
    N503[use-tabbar.ts]
    N504[index.ts]
    N505[index.ts]
    N506[index.ts]
    N507[index.ts]
    N508[index.ts]
    N509[index.ts]
    N510[index.ts]
    N511[index.ts]
    N512[index.ts]
    N513[types.ts]
    N514[index.ts]
    N515[index.ts]
    N516[index.ts]
    N517[use-open-preferences.ts]
    N518[index.ts]
    N519[index.ts]
    N520[index.ts]
    N521[echarts.ts]
    N522[index.ts]
    N523[use-echarts.ts]
    N524[index.ts]
    N525[types.ts]
    N526[api.ts]
    N527[extends.ts]
    N528[index.ts]
    N529[init.ts]
    N530[types.ts]
    N531[use-vxe-grid.ts]
    N532[index.ts]
    N533[index.ts]
    N534[downloader.test.ts]
    N535[downloader.ts]
    N536[interceptor.ts]
    N537[sse.test.ts]
    N538[sse.ts]
    N539[uploader.test.ts]
    N540[uploader.ts]
    N541[preset-interceptors.ts]
    N542[request-client.test.ts]
    N543[request-client.ts]
    N544[types.ts]
    N545[index.ts]
    N546[index.ts]
    N547[index.ts]
    N548[load.ts]
    N549[i18n.ts]
    N550[index.ts]
    N551[typing.ts]
    N552[index.ts]
    N553[shim-pinia.d.ts]
    N554[index.ts]
    N555[access.test.ts]
    N556[access.ts]
    N557[index.ts]
    N558[tabbar.test.ts]
    N559[tabbar.ts]
    N560[timezone.ts]
    N561[user.test.ts]
    N562[user.ts]
    N563[setup.ts]
    N564[index.ts]
    N565[global.d.ts]
    N566[index.ts]
    N567[user.ts]
    N568[find-menu-by-path.test.ts]
    N569[generate-menus.test.ts]
    N570[generate-routes-frontend.test.ts]
    N571[merge-route-modules.test.ts]
    N572[find-menu-by-path.ts]
    N573[generate-menus.ts]
    N574[generate-routes-backend.ts]
    N575[generate-routes-frontend.ts]
    N576[get-popup-container.ts]
    N577[index.ts]
    N578[merge-route-modules.ts]
    N579[reset-routes.ts]
    N580[unmount-global-loading.ts]
    N581[index.ts]
    N582[auth-login.spec.ts]
    N583[auth.ts]
    N584[playwright.config.ts]
    N585[index.ts]
    N586[form.ts]
    N587[vxe-table.ts]
    N588[auth.ts]
    N589[index.ts]
    N590[menu.ts]
    N591[timezone.ts]
    N592[user.ts]
    N593[download.ts]
    N594[index.ts]
    N595[json-bigint.ts]
    N596[params.ts]
    N597[status.ts]
    N598[table.ts]
    N599[upload.ts]
    N600[index.ts]
    N601[request.ts]
    N602[dept.ts]
    N603[index.ts]
    N604[menu.ts]
    N605[role.ts]
    N606[bootstrap.ts]
    N607[index.ts]
    N608[index.ts]
    N609[main.ts]
    N610[preferences.ts]
    N611[access.ts]
    N612[guard.ts]
    N613[index.ts]
    N614[core.ts]
    N615[index.ts]
    N616[dashboard.ts]
    N617[demos.ts]
    N618[examples.ts]
    N619[system.ts]
    N620[vben.ts]
    N621[auth.ts]
    N622[index.ts]
    N623[timezone-init.ts]
    N624[base64.ts]
    N625[typing.ts]
    N626[data.ts]
    N627[table-data.ts]
    N628[data.ts]
    N629[data.ts]
    N630[data.ts]
    N631[build.config.ts]
    N632[index.ts]
    N633[run.ts]
    N634[build.config.ts]
    N635[env.d.ts]
    N636[index.ts]
    N637[index.ts]
    N638[index.ts]
    N639[index.ts]
    N640[index.ts]
    N641[index.ts]
    N642[vitest.config.ts]